# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mini.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='\u5c0f\u7a0b\u5e8f\u540d\u79f0')),
                ('icon', models.FileField(help_text='\u4ee5 jpg jpeg png \u7ed3\u5c3e \u5927\u5c0f\u4e3a 60 * 60', upload_to=mini.models.mini_icon_path, verbose_name='\u5c0f\u7a0b\u5e8f\u5934\u50cf')),
                ('distribution', models.BooleanField(default=False, verbose_name='\u53d1\u5e03\u4e0a\u7ebf')),
            ],
            options={
                'verbose_name': 'React-Native-MiniInfo',
                'verbose_name_plural': 'React-Native-MiniInfo',
            },
        ),
        migrations.CreateModel(
            name='MiniModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miniId', models.CharField(help_text='\u5efa\u8bae\u4f7f\u7528 bundle ID\uff0c\u957f\u5ea6\u4e0d\u80fd\u8d85\u8fc730', max_length=30, unique=True, verbose_name='\u5c0f\u7a0b\u5e8fID')),
                ('desc', models.CharField(default='\u5f00\u53d1\u7248\u672c', max_length=50)),
                ('mobile_application_group', models.CharField(default='mini', help_text='\u4e0d\u9700\u8981\u4fee\u6539', max_length=20, verbose_name='group')),
            ],
            options={
                'verbose_name': 'React-Native-MiniModel',
                'verbose_name_plural': 'React-Native-MiniModel',
            },
        ),
        migrations.CreateModel(
            name='MiniPackageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='ios', help_text='ios or android', max_length=10, verbose_name='\u5e73\u53f0')),
                ('size', models.FloatField(verbose_name='\u6587\u4ef6\u5927\u5c0f')),
                ('path', models.FileField(help_text='\u4e0a\u4f20zip\u6587\u4ef6', upload_to=mini.models.mini_package_file_path, verbose_name='\u8def\u5f84')),
                ('forceupdate', models.BooleanField(default=False, help_text='\u8bbe\u7f6e\u4e3a\u5f3a\u5236\u66f4\u65b0\uff0c\u5c06\u4e0d\u4f1a\u4f7f\u7528\u672c\u5730\u88ab\u7f13\u5b58\u6587\u4ef6\uff08\u5f53\u672c\u5730\u7f13\u5b58\u6216\u5185\u7f6e\u7248\u672c\u5b58\u5728 bug \u65f6\u4e00\u5b9a\u7f6e\u4e3a true\uff09', verbose_name='\u662f\u5426\u5f3a\u5236\u66f4\u65b0')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('distribution', models.BooleanField(default=False, verbose_name='\u53d1\u5e03\u4e0a\u7ebf')),
                ('history', models.BooleanField(default=False, verbose_name='\u5386\u53f2\u7248\u672c')),
                ('version', models.CharField(default='no version', help_text='\u6807\u8bc6\u7248\u672c\u53f7\uff0c\u4f46\u4e0d\u4f1a\u4f5c\u4e3a\u7248\u672c\u5347\u7ea7\u4f7f\u7528', max_length=20, verbose_name='\u7248\u672c\u53f7')),
                ('versiondesc', models.CharField(default='\u65b0\u7248\u672c', max_length=50, verbose_name='\u53d1\u7248\u8bf4\u660e')),
                ('fullupdate', models.BooleanField(default=False, help_text='\u662f\u5426\u662f\u6574\u5305\u5347\u7ea7\uff08\u8bbe\u7f6e\u4e3aTrue\u65f6\uff0c\u4e0d\u4f1a\u8bfb\u53d6\u8865\u4e01\u5305\uff09', verbose_name='\u6574\u5305\u5347\u7ea7')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_package_product', to='mini.MiniModel', verbose_name='\u5173\u8054\u4ea7\u54c1')),
            ],
            options={
                'verbose_name': 'React-Native-MiniPackage',
                'verbose_name_plural': 'React-Native-MiniPackage',
            },
        ),
        migrations.AddField(
            model_name='miniinfomodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_info_product', to='mini.MiniModel', verbose_name='\u5173\u8054\u5c0f\u7a0b\u5e8f'),
        ),
    ]
